# Generated by Django 6.0.7 on 2026-08-12 02:11
# Squashes api.migrations 0001_initial through
# 0020_remove_elasticsearchindex_only_published into one migration. The three
# RunPython data-seed functions below are copied in by hand from
# 0014_seed_metadata_types, 0016_seed_elasticsearch_indexes and
# 0019_seed_bounding_box_field_maps (Django's squasher can't safely copy
# function code across migration modules on its own).

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_metadata_types(apps, schema_editor):
    MetadataType = apps.get_model("api", "MetadataType")
    MetadataRecord = apps.get_model("api", "MetadataRecord")

    oceanography, _ = MetadataType.objects.get_or_create(metadata_type_value="Oceanography")
    MetadataType.objects.get_or_create(metadata_type_value="Drone")

    # Every record that exists today predates this field - all of it is
    # oceanographic data, per the user's own call.
    MetadataRecord.objects.filter(metadata_type__isnull=True).update(metadata_type=oceanography)


def unseed_metadata_types(apps, schema_editor):
    MetadataType = apps.get_model("api", "MetadataType")
    MetadataRecord = apps.get_model("api", "MetadataRecord")
    MetadataRecord.objects.all().update(metadata_type=None)
    MetadataType.objects.filter(metadata_type_value__in=["Oceanography", "Drone"]).delete()


# (source, target, es_type) - target="" falls back to the model's own
# default (source path with dots replaced by underscores). Mirrors, at a
# simpler level, what the legacy backend's default column set exposed.
DEFAULT_FIELDS = [
    ("title", "", "text"),
    ("abstract", "", "text"),
    ("contact.firstname", "", "text"),
    ("contact.lastname", "", "text"),
    ("contact.email", "", "keyword"),
    ("contact.position", "", "text"),
    ("country.short_name", "", "keyword"),
    ("country.long_name", "", "keyword"),
    ("publisher.publisher_value", "publisher_value", "keyword"),
    ("topic.topic_value", "topic_value", "keyword"),
    ("keywords.keyword_value", "keywords", "keyword"),
    ("temporal_coverage_from", "", "date"),
    ("temporal_coverage_to", "", "date"),
    ("access_constraints", "", "keyword"),
    ("license", "", "text"),
    (
        "spatial_representation_type.spatial_representation_type_value",
        "spatial_representation_type",
        "keyword",
    ),
    ("coordinate_reference_system.crs_value", "crs_value", "keyword"),
    ("data_type.data_type_value", "data_type_value", "keyword"),
    ("metadata_type.metadata_type_value", "metadata_type_value", "keyword"),
]


def seed_indexes(apps, schema_editor):
    MetadataType = apps.get_model("api", "MetadataType")
    ElasticsearchIndex = apps.get_model("api", "ElasticsearchIndex")
    ElasticsearchFieldMap = apps.get_model("api", "ElasticsearchFieldMap")

    for type_value, index_name in [("Oceanography", "oceanography"), ("Drone", "drone")]:
        metadata_type = MetadataType.objects.get(metadata_type_value=type_value)
        index, _ = ElasticsearchIndex.objects.get_or_create(
            metadata_type=metadata_type,
            defaults={"name": type_value, "index_name": index_name},
        )
        for order, (source, target, es_type) in enumerate(DEFAULT_FIELDS):
            ElasticsearchFieldMap.objects.get_or_create(
                index=index,
                source=source,
                defaults={"target": target, "es_type": es_type, "order": order},
            )


def unseed_indexes(apps, schema_editor):
    ElasticsearchIndex = apps.get_model("api", "ElasticsearchIndex")
    ElasticsearchIndex.objects.filter(name__in=["Oceanography", "Drone"]).delete()


BOUNDING_BOX_FIELDS = [
    ("west_bound_longitude", "west_bounding_longitude", "float"),
    ("east_bound_longitude", "east_bounding_longitude", "float"),
    ("south_bound_latitude", "south_bounding_latitude", "float"),
    ("north_bound_latitude", "north_bounding_latitude", "float"),
]


def add_bounding_box_fields(apps, schema_editor):
    ElasticsearchIndex = apps.get_model("api", "ElasticsearchIndex")
    ElasticsearchFieldMap = apps.get_model("api", "ElasticsearchFieldMap")

    for index in ElasticsearchIndex.objects.all():
        for offset, (source, target, es_type) in enumerate(BOUNDING_BOX_FIELDS):
            ElasticsearchFieldMap.objects.get_or_create(
                index=index,
                source=source,
                defaults={"target": target, "es_type": es_type, "order": 100 + offset},
            )


def remove_bounding_box_fields(apps, schema_editor):
    ElasticsearchFieldMap = apps.get_model("api", "ElasticsearchFieldMap")
    ElasticsearchFieldMap.objects.filter(
        source__in=[source for source, _, _ in BOUNDING_BOX_FIELDS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetadataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('creator', models.CharField(help_text='Person/organisation responsible', max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateField(help_text='Date the described resource was created')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='List of keyword strings')),
                ('language', models.CharField(default='en', max_length=20)),
                ('rights', models.CharField(blank=True, help_text='Licence / usage rights', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict, help_text="Values for the template's fields")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_records', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='api.metadatatemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Machine key used inside record data', max_length=100)),
                ('label', models.CharField(help_text='Human-friendly label', max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('field_type', models.CharField(choices=[('text', 'Text (single line)'), ('textarea', 'Text (multi-line)'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean (yes/no)'), ('date', 'Date'), ('datetime', 'Date & time'), ('url', 'URL'), ('email', 'Email'), ('select', 'Select (one choice)'), ('multiselect', 'Select (many choices)')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, default=list, help_text='Allowed values for (multi)select fields')),
                ('default', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.metadatatemplate')),
            ],
            options={
                'ordering': ['template', 'order', 'id'],
                'unique_together': {('template', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RecordRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('derived_from', 'Is derived from'), ('part_of', 'Is part of'), ('references', 'References'), ('replaces', 'Replaces'), ('related_to', 'Is related to')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='api.metadatarecord')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='api.metadatarecord')),
            ],
            options={
                'unique_together': {('source', 'target', 'relation_type')},
            },
        ),
        migrations.DeleteModel(
            name='RecordRelationship',
        ),
        migrations.AlterField(
            model_name='fielddefinition',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text (single line)'), ('textarea', 'Text (multi-line)'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean (yes/no)'), ('date', 'Date'), ('datetime', 'Date & time'), ('url', 'URL'), ('email', 'Email'), ('select', 'Select (one choice)'), ('multiselect', 'Select (many choices)'), ('file', 'File upload'), ('image', 'Image upload')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='CoordinateReferenceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_value', models.CharField(max_length=100, unique=True)),
                ('crs_description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'coordinate reference system',
                'verbose_name_plural': 'coordinate reference systems',
                'ordering': ['crs_value'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='e.g. FJ', max_length=10, unique=True)),
                ('long_name', models.CharField(help_text='e.g. Fiji', max_length=255)),
                ('west_bound_longitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('east_bound_longitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('south_bound_latitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('north_bound_latitude', models.DecimalField(decimal_places=5, max_digits=9)),
                ('crs_name', models.CharField(help_text='CRS the bounds are given in', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['long_name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['keyword_value'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_value', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['publisher_value'],
            },
        ),
        migrations.CreateModel(
            name='SpatialRepresentationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spatial_representation_type_value', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'spatial representation type',
                'verbose_name_plural': 'spatial representation types',
                'ordering': ['spatial_representation_type_value'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['topic_value'],
            },
        ),
        migrations.RemoveField(
            model_name='metadatarecord',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='metadatarecord',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='metadatarecord',
            name='description',
        ),
        migrations.RemoveField(
            model_name='metadatarecord',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='metadatarecord',
            name='rights',
        ),
        migrations.RemoveField(
            model_name='metadatarecord',
            name='publisher',
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='abstract',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='access_constraints',
            field=models.CharField(choices=[('private', 'Private'), ('open', 'Open')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='license',
            field=models.CharField(default='Other (Not Open)', max_length=255),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='lineage',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='metadata_standard_language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='metadata_standard_name',
            field=models.CharField(default='MEDIN', max_length=100),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='metadata_standard_version',
            field=models.CharField(default='3.1.2', max_length=50),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='temporal_coverage_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='temporal_coverage_to',
            field=models.DateField(blank=True, help_text='Leave empty if coverage is ongoing', null=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='update_frequency',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='version',
            field=models.CharField(default='1.0.0', max_length=50),
        ),
        migrations.RemoveField(
            model_name='metadatarecord',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='metadatarecord',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='contact',
            field=models.ForeignKey(default=1, help_text='Person to contact about this record', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='coordinate_reference_system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.coordinatereferencesystem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='country',
            field=models.ForeignKey(default=1, help_text='Supplies the geographic bounding box and its CRS name', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.publisher'),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='spatial_representation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.spatialrepresentationtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.topic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='api.keyword'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['project_name'],
            },
        ),
        migrations.AlterField(
            model_name='fielddefinition',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text (single line)'), ('textarea', 'Text (multi-line)'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean (yes/no)'), ('date', 'Date'), ('datetime', 'Date & time'), ('url', 'URL'), ('email', 'Email'), ('select', 'Select (one choice)'), ('multiselect', 'Select (many choices)'), ('file', 'File upload'), ('image', 'Image upload'), ('project', 'Project (lookup)')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='ElasticsearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Internal label', max_length=255, unique=True)),
                ('index_name', models.CharField(help_text='Elasticsearch index to write into, e.g. dms-records', max_length=255)),
                ('only_published', models.BooleanField(default=True, help_text='Send published records only')),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(blank=True, help_text='Limit to records of this template; empty means all templates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elasticsearch_indexes', to='api.metadatatemplate')),
            ],
            options={
                'verbose_name': 'Elasticsearch index',
                'verbose_name_plural': 'Elasticsearch indexes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ElasticsearchFieldMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Dotted path on the record: a core field (title), a related lookup attribute (country.long_name), or a template value (data.project)', max_length=200)),
                ('target', models.CharField(blank=True, help_text='Key in the Elasticsearch document; defaults to the source path with dots replaced by underscores', max_length=200)),
                ('es_type', models.CharField(choices=[('text', 'text'), ('keyword', 'keyword'), ('integer', 'integer'), ('float', 'float'), ('boolean', 'boolean'), ('date', 'date'), ('geo_shape', 'geo_shape')], default='text', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.elasticsearchindex')),
            ],
            options={
                'verbose_name': 'Elasticsearch field',
                'verbose_name_plural': 'Elasticsearch fields',
                'ordering': ['index', 'order', 'id'],
                'unique_together': {('index', 'source')},
            },
        ),
        migrations.AlterField(
            model_name='elasticsearchfieldmap',
            name='source',
            field=models.CharField(choices=[('id', 'id'), ('title', 'title'), ('abstract', 'abstract'), ('contact.firstname', 'contact — firstname'), ('contact.lastname', 'contact — lastname'), ('contact.email', 'contact — email'), ('contact.position', 'contact — position'), ('contact.organization', 'contact — organization'), ('language', 'language'), ('version', 'version'), ('country.short_name', 'country — short_name'), ('country.long_name', 'country — long_name'), ('west_bound_longitude', 'west_bound_longitude'), ('east_bound_longitude', 'east_bound_longitude'), ('south_bound_latitude', 'south_bound_latitude'), ('north_bound_latitude', 'north_bound_latitude'), ('crs_name', 'crs_name'), ('coordinate_reference_system.crs_value', 'crs_value'), ('coordinate_reference_system.crs_description', 'crs_description'), ('publisher.publisher_value', 'publisher — publisher_value'), ('publisher.website', 'publisher — website'), ('publisher.email', 'publisher — email'), ('topic.topic_value', 'topic — topic_value'), ('keywords.keyword_value', 'keywords — keyword_value (list)'), ('access_constraints', 'access_constraints'), ('license', 'license'), ('temporal_coverage_from', 'temporal_coverage_from'), ('temporal_coverage_to', 'temporal_coverage_to'), ('metadata_standard_name', 'metadata_standard_name'), ('metadata_standard_version', 'metadata_standard_version'), ('metadata_standard_language', 'metadata_standard_language'), ('update_frequency', 'update_frequency'), ('lineage', 'lineage'), ('spatial_representation_type.spatial_representation_type_value', 'spatial_representation_type_value'), ('status', 'status'), ('created_at', 'created_at'), ('updated_at', 'updated_at')], help_text='Field of the metadata record to send', max_length=200),
        ),
        migrations.AlterField(
            model_name='elasticsearchindex',
            name='template',
            field=models.ForeignKey(blank=True, help_text="Limit which records are indexed to this template; empty means records of every template. Template ('data') fields are never sent.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elasticsearch_indexes', to='api.metadatatemplate'),
        ),
        migrations.RemoveField(
            model_name='elasticsearchindex',
            name='template',
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type_value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'data type',
                'verbose_name_plural': 'data types',
                'ordering': ['data_type_value'],
            },
        ),
        migrations.AlterModelOptions(
            name='metadatarecord',
            options={'ordering': ['-created_at'], 'permissions': [('approve_metadatarecord', 'Can approve or reject metadata records')]},
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='acknowledgement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='acquisition_report_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='action_history',
            field=models.JSONField(blank=True, default=list, help_text='Audit log of submit/approve/reject actions on this record'),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='attribute',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='factsheet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='file_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='file_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='file_upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='fundings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='link_to_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='project_report_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Who approved or rejected this record, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_metadata_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metadatarecord',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Who created/submitted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metadatarecord',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.datatype'),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='data_format',
            field=models.CharField(default='GIS', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coordinatereferencesystem',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='datatype',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coordinatereferencesystem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coordinatereferencesystem',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='datatype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='datatype',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='keyword',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='keyword',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publisher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publisher',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='spatialrepresentationtype',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MetadataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata_type_value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'metadata type',
                'verbose_name_plural': 'metadata types',
                'ordering': ['metadata_type_value'],
            },
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='metadata_type',
            field=models.ForeignKey(blank=True, help_text='Top-level category of this record, e.g. Oceanography, Drone', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.metadatatype'),
        ),
        migrations.RunPython(
            code=seed_metadata_types,
            reverse_code=unseed_metadata_types,
        ),
        migrations.AddField(
            model_name='elasticsearchindex',
            name='metadata_type',
            field=models.OneToOneField(default=1, help_text='Records of this type sync to this index, and no other', on_delete=django.db.models.deletion.CASCADE, related_name='elasticsearch_index', to='api.metadatatype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elasticsearchfieldmap',
            name='source',
            field=models.CharField(choices=[('id', 'id'), ('title', 'title'), ('abstract', 'abstract'), ('contact.firstname', 'contact — firstname'), ('contact.lastname', 'contact — lastname'), ('contact.email', 'contact — email'), ('contact.position', 'contact — position'), ('contact.organization', 'contact — organization'), ('language', 'language'), ('version', 'version'), ('country.short_name', 'country — short_name'), ('country.long_name', 'country — long_name'), ('west_bound_longitude', 'west_bound_longitude'), ('east_bound_longitude', 'east_bound_longitude'), ('south_bound_latitude', 'south_bound_latitude'), ('north_bound_latitude', 'north_bound_latitude'), ('crs_name', 'crs_name'), ('coordinate_reference_system.crs_value', 'crs_value'), ('coordinate_reference_system.crs_description', 'crs_description'), ('publisher.publisher_value', 'publisher — publisher_value'), ('publisher.website', 'publisher — website'), ('publisher.email', 'publisher — email'), ('topic.topic_value', 'topic — topic_value'), ('keywords.keyword_value', 'keywords — keyword_value (list)'), ('access_constraints', 'access_constraints'), ('license', 'license'), ('temporal_coverage_from', 'temporal_coverage_from'), ('temporal_coverage_to', 'temporal_coverage_to'), ('metadata_standard_name', 'metadata_standard_name'), ('metadata_standard_version', 'metadata_standard_version'), ('metadata_standard_language', 'metadata_standard_language'), ('update_frequency', 'update_frequency'), ('lineage', 'lineage'), ('spatial_representation_type.spatial_representation_type_value', 'spatial_representation_type_value'), ('status', 'status'), ('created_at', 'created_at'), ('updated_at', 'updated_at'), ('comment', 'comment'), ('link_to_data', 'link_to_data'), ('acquisition_report_link', 'acquisition_report_link'), ('project_report_link', 'project_report_link'), ('factsheet', 'factsheet'), ('fundings', 'fundings'), ('references', 'references'), ('acknowledgement', 'acknowledgement'), ('history', 'history'), ('data_type.data_type_value', 'data_type — data_type_value'), ('metadata_type.metadata_type_value', 'metadata_type — metadata_type_value')], help_text='Field of the metadata record to send', max_length=200),
        ),
        migrations.AlterField(
            model_name='elasticsearchindex',
            name='index_name',
            field=models.CharField(help_text='Elasticsearch index to write into, e.g. oceanography', max_length=255),
        ),
        migrations.RunPython(
            code=seed_indexes,
            reverse_code=unseed_indexes,
        ),
        migrations.RemoveField(
            model_name='metadatarecord',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='metadatarecord',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='metadatarecord',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='metadatarecord',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='metadatarecord',
            name='file_upload_date',
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='metadata_files/'),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='boundary_type',
            field=models.CharField(choices=[('zone', 'Zone (bounding box)'), ('point', 'Point')], default='zone', help_text="Whether this record's own boundary (if set) is a zone (bounding box) or a single point", max_length=10),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='east_bounding_longitude',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Zone only: east edge. Ignored for a point.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='north_bounding_latitude',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Zone only: north edge. Ignored for a point.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='south_bounding_latitude',
            field=models.DecimalField(blank=True, decimal_places=5, help_text="Zone: south edge. Point: the point's latitude.", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='west_bounding_longitude',
            field=models.DecimalField(blank=True, decimal_places=5, help_text="Zone: west edge. Point: the point's longitude.", max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='elasticsearchfieldmap',
            name='source',
            field=models.CharField(choices=[('id', 'id'), ('title', 'title'), ('abstract', 'abstract'), ('contact.firstname', 'contact — firstname'), ('contact.lastname', 'contact — lastname'), ('contact.email', 'contact — email'), ('contact.position', 'contact — position'), ('contact.organization', 'contact — organization'), ('language', 'language'), ('version', 'version'), ('country.short_name', 'country — short_name'), ('country.long_name', 'country — long_name'), ('west_bound_longitude', 'west_bound_longitude'), ('east_bound_longitude', 'east_bound_longitude'), ('south_bound_latitude', 'south_bound_latitude'), ('north_bound_latitude', 'north_bound_latitude'), ('boundary_type', 'boundary_type (zone/point)'), ('crs_name', 'crs_name'), ('coordinate_reference_system.crs_value', 'crs_value'), ('coordinate_reference_system.crs_description', 'crs_description'), ('publisher.publisher_value', 'publisher — publisher_value'), ('publisher.website', 'publisher — website'), ('publisher.email', 'publisher — email'), ('topic.topic_value', 'topic — topic_value'), ('keywords.keyword_value', 'keywords — keyword_value (list)'), ('access_constraints', 'access_constraints'), ('license', 'license'), ('temporal_coverage_from', 'temporal_coverage_from'), ('temporal_coverage_to', 'temporal_coverage_to'), ('metadata_standard_name', 'metadata_standard_name'), ('metadata_standard_version', 'metadata_standard_version'), ('metadata_standard_language', 'metadata_standard_language'), ('update_frequency', 'update_frequency'), ('lineage', 'lineage'), ('spatial_representation_type.spatial_representation_type_value', 'spatial_representation_type_value'), ('status', 'status'), ('created_at', 'created_at'), ('updated_at', 'updated_at'), ('comment', 'comment'), ('link_to_data', 'link_to_data'), ('acquisition_report_link', 'acquisition_report_link'), ('project_report_link', 'project_report_link'), ('factsheet', 'factsheet'), ('fundings', 'fundings'), ('references', 'references'), ('acknowledgement', 'acknowledgement'), ('history', 'history'), ('data_type.data_type_value', 'data_type — data_type_value'), ('metadata_type.metadata_type_value', 'metadata_type — metadata_type_value')], help_text='Field of the metadata record to send', max_length=200),
        ),
        migrations.AlterField(
            model_name='metadatarecord',
            name='country',
            field=models.ForeignKey(help_text='Supplies the geographic bounding box and its CRS name, unless overridden below', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.country'),
        ),
        migrations.RunPython(
            code=add_bounding_box_fields,
            reverse_code=remove_bounding_box_fields,
        ),
        migrations.RemoveField(
            model_name='elasticsearchindex',
            name='only_published',
        ),
    ]
