# Generated by Django 6.0.7 on 2026-09-14 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatarecord',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this record is attributed to, if any', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.project'),
        ),
        migrations.AlterField(
            model_name='elasticsearchfieldmap',
            name='source',
            field=models.CharField(choices=[('id', 'id'), ('title', 'title'), ('abstract', 'abstract'), ('contact.firstname', 'contact — firstname'), ('contact.lastname', 'contact — lastname'), ('contact.email', 'contact — email'), ('contact.position', 'contact — position'), ('contact.organization', 'contact — organization'), ('language', 'language'), ('version', 'version'), ('country.short_name', 'country — short_name'), ('country.long_name', 'country — long_name'), ('west_bound_longitude', 'west_bound_longitude'), ('east_bound_longitude', 'east_bound_longitude'), ('south_bound_latitude', 'south_bound_latitude'), ('north_bound_latitude', 'north_bound_latitude'), ('boundary_type', 'boundary_type (zone/point)'), ('crs_name', 'crs_name'), ('coordinate_reference_system.crs_value', 'crs_value'), ('coordinate_reference_system.crs_description', 'crs_description'), ('publisher.publisher_value', 'publisher — publisher_value'), ('publisher.website', 'publisher — website'), ('publisher.email', 'publisher — email'), ('topic.topic_value', 'topic — topic_value'), ('keywords.keyword_value', 'keywords — keyword_value (list)'), ('access_constraints', 'access_constraints'), ('license', 'license'), ('temporal_coverage_from', 'temporal_coverage_from'), ('temporal_coverage_to', 'temporal_coverage_to'), ('metadata_standard_name', 'metadata_standard_name'), ('metadata_standard_version', 'metadata_standard_version'), ('metadata_standard_language', 'metadata_standard_language'), ('update_frequency', 'update_frequency'), ('lineage', 'lineage'), ('spatial_representation_type.spatial_representation_type_value', 'spatial_representation_type_value'), ('status', 'status'), ('created_at', 'created_at'), ('updated_at', 'updated_at'), ('comment', 'comment'), ('link_to_data', 'link_to_data'), ('acquisition_report_link', 'acquisition_report_link'), ('project_report_link', 'project_report_link'), ('factsheet', 'factsheet'), ('fundings', 'fundings'), ('references', 'references'), ('acknowledgement', 'acknowledgement'), ('history', 'history'), ('data_type.data_type_value', 'data_type — data_type_value'), ('project.project_name', 'project — project_name'), ('project.project_code', 'project — project_code'), ('metadata_type.metadata_type_value', 'metadata_type — metadata_type_value')], help_text='Field of the metadata record to send', max_length=200),
        ),
        migrations.AlterField(
            model_name='fielddefinition',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text (single line)'), ('textarea', 'Text (multi-line)'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean (yes/no)'), ('date', 'Date'), ('datetime', 'Date & time'), ('url', 'URL'), ('email', 'Email'), ('select', 'Select (one choice)'), ('multiselect', 'Select (many choices)'), ('file', 'File upload'), ('image', 'Image upload')], default='text', max_length=20),
        ),
    ]
