# Generated by Django 6.0.7 on 2026-09-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_migrate_project_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticsearchfieldmap',
            name='source',
            field=models.CharField(help_text="Field of the metadata record to send - a core field (see RECORD_SOURCE_CHOICES) or data.<name> for one of the active template's own fields. The admin form offers both as a dropdown.", max_length=200),
        ),
    ]
