# Generated by Django 6.0.7 on 2026-09-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_free_form_es_source_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticsearchfieldmap',
            name='target',
            field=models.CharField(blank=True, help_text='Key in the Elasticsearch document; defaults to the source path with dots replaced by underscores. Give two fields the same dotted prefix (e.g. contacts.Name and contacts.Email) to group them into one nested object, shown as one labelled block instead of separate rows.', max_length=200),
        ),
    ]
