# Generated by Django 6.0.7 on 2026-09-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_elasticsearchfieldmap_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatarecord',
            name='additional_information',
            field=models.TextField(blank=True, help_text='A supplementary document/report link for this record'),
        ),
    ]
