# Generated by Django 6.0.7 on 2026-09-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatarecord',
            name='acquisition_report_file',
            field=models.FileField(blank=True, null=True, upload_to='acquisition_reports/'),
        ),
        migrations.AddField(
            model_name='metadatarecord',
            name='additional_information_file',
            field=models.FileField(blank=True, help_text='Upload instead of (or in addition to) a link above - the upload wins if both are set', null=True, upload_to='additional_information/'),
        ),
    ]
