"""Keeps pygeoapi's config in sync with the ElasticsearchIndex rows managed
in the Django admin - one pygeoapi collection per active index, generated
automatically instead of hand-edited (see the "resources:" comment that used
to live in pygeoapi-config.yml). Wired via post_save/post_delete on
ElasticsearchIndex in api/signals.py.

pygeoapi (pygeoapi/main.py) only reads its config once at process startup,
so a regenerated file has no effect until the process restarts - see
restart_pygeoapi() below for the (best-effort, local-dev-only) other half of
that.
"""

import logging
import platform
import subprocess
from urllib.parse import urlsplit

from django.conf import settings
from django.utils.text import slugify
from ruamel.yaml import YAML

from .models import ElasticsearchIndex

logger = logging.getLogger(__name__)

_yaml = YAML()
_yaml.preserve_quotes = True
_yaml.width = 4096  # don't wrap the long provider data: URLs

_RESOURCES_COMMENT = (
    "One resource per active ElasticsearchIndex row, auto-generated by "
    "backend/api/pygeoapi_sync.py whenever one is created/edited/deleted "
    "in the Django admin - do not add blocks here by hand, they will be "
    "overwritten. title/description/keywords on an existing block ARE "
    "preserved across regeneration, so those are still safe to hand-tune."
)


def _resource_key(index):
    return slugify(index.metadata_type.metadata_type_value) or slugify(index.name)


def _es_base(host, port, scheme="http"):
    username = getattr(settings, "ELASTICSEARCH_USERNAME", "") or ""
    password = getattr(settings, "ELASTICSEARCH_PASSWORD", "") or ""
    auth = f"{username}:{password}@" if username else ""
    return f"{scheme}://{auth}{host}:{port}"


def _build_resource(index, es_base, existing):
    """One pygeoapi `resources.<key>` entry for `index`. title/description/
    keywords come from the file's existing block when there is one (they're
    hand-curated, not modeled on ElasticsearchIndex); only the provider URL
    and the set of resources itself always track the database.
    """
    existing = existing or {}
    return {
        "type": "collection",
        "title": existing.get("title", f"{index.name} Metadata records"),
        "description": existing.get(
            "description", f"{index.name} metadata records from the DMS system"
        ),
        "keywords": existing.get("keywords", [slugify(index.name)]),
        "extents": existing.get(
            "extents",
            {
                "spatial": {
                    "bbox": [-180, -90, 180, 90],
                    "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
                }
            },
        ),
        "providers": [
            {
                "type": "record",
                "name": "ElasticsearchCatalogue",
                "data": f"{es_base}/{index.index_name}",
                "id_field": "id",
                "title_field": "title",
            }
        ],
    }


def _regenerate_file(path, es_base):
    if not path.exists():
        logger.warning("pygeoapi config not found, skipping: %s", path)
        return

    original_bytes = path.read_bytes()
    uses_crlf = b"\r\n" in original_bytes

    with path.open("r", encoding="utf-8") as fh:
        config = _yaml.load(fh)

    existing_resources = config.get("resources") or {}
    indexes = ElasticsearchIndex.objects.filter(is_active=True).select_related("metadata_type")

    resources = {}
    for index in indexes:
        key = _resource_key(index)
        resources[key] = _build_resource(index, es_base, existing_resources.get(key))

    config["resources"] = resources
    # Clear whatever comment used to sit between "resources:" and its first
    # child (e.g. the old hand-written "add a block here" instructions) -
    # ruamel keys comments by the *key name*, not the value object, so simply
    # replacing config["resources"] above does not drop it on its own.
    config.ca.items.pop("resources", None)
    config.yaml_set_comment_before_after_key("resources", before="\n" + _RESOURCES_COMMENT)

    if uses_crlf:
        import io

        buf = io.StringIO()
        _yaml.dump(config, buf)
        path.write_text(buf.getvalue().replace("\n", "\r\n"), encoding="utf-8")
    else:
        with path.open("w", encoding="utf-8") as fh:
            _yaml.dump(config, fh)


def _active_es_host_port():
    """The ES host/port this Django process is itself configured to use -
    what the currently-active pygeoapi-config.yml (whichever mode the repo
    is in right now) should point at."""
    parsed = urlsplit(settings.ELASTICSEARCH_URL)
    return parsed.hostname or "localhost", parsed.port or 9200


def regenerate_all():
    """Rewrite every pygeoapi config variant's `resources` section from the
    ElasticsearchIndex rows currently in the database.

    All three files (active + .local + .docker) are updated together, not
    just the active one - dev.py's local/docker mode switch overwrites
    pygeoapi-config.yml from whichever *.yml.<mode> variant, so leaving
    those stale would silently revert the resources list on the next switch.
    """
    config_dir = settings.PYGEOAPI_DIR / "pygeoapi-generate-config"
    active_host, active_port = _active_es_host_port()

    _regenerate_file(config_dir / "pygeoapi-config.yml.local", _es_base("localhost", 9200))
    _regenerate_file(config_dir / "pygeoapi-config.yml.docker", _es_base("elasticsearch", 9200))
    _regenerate_file(config_dir / "pygeoapi-config.yml", _es_base(active_host, active_port))


def _to_wsl_path(windows_path):
    """C:\\Code\\dms_new\\pygeoapi -> /mnt/c/Code/dms_new/pygeoapi"""
    text = str(windows_path)
    drive, rest = text[0].lower(), text[2:].replace("\\", "/")
    return f"/mnt/{drive}{rest}"


def _restart_command():
    override = getattr(settings, "PYGEOAPI_RESTART_COMMAND", "") or ""
    if override:
        return override.split()

    script = settings.PYGEOAPI_DIR / "restart.sh"
    if platform.system() == "Windows":
        # Django running natively on Windows rather than the WSL Ubuntu
        # dev.py normally launches it in - hop into that same distro.
        return ["wsl.exe", "-d", "Ubuntu", "bash", _to_wsl_path(script)]
    return ["bash", str(script)]


def restart_pygeoapi():
    if not getattr(settings, "PYGEOAPI_AUTO_RESTART", True):
        return
    try:
        subprocess.Popen(_restart_command())
    except Exception:
        logger.exception("Failed to restart pygeoapi")


def sync_pygeoapi():
    """Regenerate config + restart pygeoapi. Best-effort: never raises, so
    saving an ElasticsearchIndex in the admin can't 500 because pygeoapi (or
    its filesystem) happens to be unreachable."""
    try:
        regenerate_all()
    except Exception:
        logger.exception("Failed to regenerate pygeoapi config")
        return
    restart_pygeoapi()
