--
-- PostgreSQL database dump
--

\restrict CiH6pyIUj5DJZhjoVGwITeWQ2Rdm3DfPvssPOPOmy75U0UZiYk4kz7XANf5SItH

-- Dumped from database version 16.13 (Homebrew)
-- Dumped by pg_dump version 16.13 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api_contact; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_contact (
    id bigint NOT NULL,
    firstname character varying(150) NOT NULL,
    lastname character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    "position" character varying(255) NOT NULL,
    organization character varying(255) NOT NULL
);


ALTER TABLE public.api_contact OWNER TO postgres;

--
-- Name: api_contact_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_contact ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_coordinatereferencesystem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_coordinatereferencesystem (
    id bigint NOT NULL,
    crs_value character varying(100) NOT NULL,
    crs_description character varying(500) NOT NULL
);


ALTER TABLE public.api_coordinatereferencesystem OWNER TO postgres;

--
-- Name: api_coordinatereferencesystem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_coordinatereferencesystem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_coordinatereferencesystem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_country; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_country (
    id bigint NOT NULL,
    short_name character varying(10) NOT NULL,
    long_name character varying(255) NOT NULL,
    west_bound_longitude numeric(9,5) NOT NULL,
    east_bound_longitude numeric(9,5) NOT NULL,
    south_bound_latitude numeric(9,5) NOT NULL,
    north_bound_latitude numeric(9,5) NOT NULL,
    crs_name character varying(255) NOT NULL
);


ALTER TABLE public.api_country OWNER TO postgres;

--
-- Name: api_country_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_country ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_country_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_fielddefinition; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_fielddefinition (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    label character varying(255) NOT NULL,
    help_text character varying(500) NOT NULL,
    field_type character varying(20) NOT NULL,
    required boolean NOT NULL,
    choices jsonb NOT NULL,
    "default" jsonb,
    "order" integer NOT NULL,
    template_id bigint NOT NULL,
    CONSTRAINT api_fielddefinition_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.api_fielddefinition OWNER TO postgres;

--
-- Name: api_fielddefinition_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_fielddefinition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_fielddefinition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_keyword; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_keyword (
    id bigint NOT NULL,
    keyword_value character varying(255) NOT NULL
);


ALTER TABLE public.api_keyword OWNER TO postgres;

--
-- Name: api_keyword_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_keyword ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_keyword_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_metadatarecord; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_metadatarecord (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title character varying(500) NOT NULL,
    language character varying(100) NOT NULL,
    data jsonb NOT NULL,
    status character varying(20) NOT NULL,
    owner_id integer,
    template_id bigint NOT NULL,
    abstract text NOT NULL,
    access_constraints character varying(20) NOT NULL,
    license character varying(255) NOT NULL,
    lineage text NOT NULL,
    metadata_standard_language character varying(100) NOT NULL,
    metadata_standard_name character varying(100) NOT NULL,
    metadata_standard_version character varying(50) NOT NULL,
    temporal_coverage_from date,
    temporal_coverage_to date,
    update_frequency character varying(255) NOT NULL,
    version character varying(50) NOT NULL,
    contact_id bigint NOT NULL,
    coordinate_reference_system_id bigint NOT NULL,
    country_id bigint NOT NULL,
    publisher_id bigint NOT NULL,
    spatial_representation_type_id bigint NOT NULL,
    topic_id bigint NOT NULL
);


ALTER TABLE public.api_metadatarecord OWNER TO postgres;

--
-- Name: api_metadatarecord_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_metadatarecord ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_metadatarecord_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_metadatarecord_keywords; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_metadatarecord_keywords (
    id bigint NOT NULL,
    metadatarecord_id bigint NOT NULL,
    keyword_id bigint NOT NULL
);


ALTER TABLE public.api_metadatarecord_keywords OWNER TO postgres;

--
-- Name: api_metadatarecord_keywords_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_metadatarecord_keywords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_metadatarecord_keywords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_metadatatemplate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_metadatatemplate (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    description text NOT NULL,
    version integer NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT api_metadatatemplate_version_check CHECK ((version >= 0))
);


ALTER TABLE public.api_metadatatemplate OWNER TO postgres;

--
-- Name: api_metadatatemplate_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_metadatatemplate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_metadatatemplate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_project; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_project (
    id bigint NOT NULL,
    project_name character varying(255) NOT NULL,
    project_code character varying(50) NOT NULL,
    comments text NOT NULL
);


ALTER TABLE public.api_project OWNER TO postgres;

--
-- Name: api_project_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_publisher; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_publisher (
    id bigint NOT NULL,
    publisher_value character varying(255) NOT NULL,
    website character varying(200) NOT NULL,
    email character varying(254) NOT NULL
);


ALTER TABLE public.api_publisher OWNER TO postgres;

--
-- Name: api_publisher_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_publisher ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_publisher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_spatialrepresentationtype; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_spatialrepresentationtype (
    id bigint NOT NULL,
    spatial_representation_type_value character varying(100) NOT NULL
);


ALTER TABLE public.api_spatialrepresentationtype OWNER TO postgres;

--
-- Name: api_spatialrepresentationtype_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_spatialrepresentationtype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_spatialrepresentationtype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_topic; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_topic (
    id bigint NOT NULL,
    topic_value character varying(255) NOT NULL
);


ALTER TABLE public.api_topic OWNER TO postgres;

--
-- Name: api_topic_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_topic ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_topic_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Data for Name: api_contact; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_contact (id, firstname, lastname, email, "position", organization) FROM stdin;
\.


--
-- Data for Name: api_coordinatereferencesystem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_coordinatereferencesystem (id, crs_value, crs_description) FROM stdin;
\.


--
-- Data for Name: api_country; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_country (id, short_name, long_name, west_bound_longitude, east_bound_longitude, south_bound_latitude, north_bound_latitude, crs_name) FROM stdin;
\.


--
-- Data for Name: api_fielddefinition; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_fielddefinition (id, name, label, help_text, field_type, required, choices, "default", "order", template_id) FROM stdin;
21	acquisition_report_link	Report Acquisition Link		url	f	[]	\N	1	11
22	additional_information	additional information		url	f	[]	\N	0	11
23	project_name	Project Name		project	f	[]	\N	0	11
\.


--
-- Data for Name: api_keyword; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_keyword (id, keyword_value) FROM stdin;
\.


--
-- Data for Name: api_metadatarecord; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_metadatarecord (id, created_at, updated_at, title, language, data, status, owner_id, template_id, abstract, access_constraints, license, lineage, metadata_standard_language, metadata_standard_name, metadata_standard_version, temporal_coverage_from, temporal_coverage_to, update_frequency, version, contact_id, coordinate_reference_system_id, country_id, publisher_id, spatial_representation_type_id, topic_id) FROM stdin;
\.


--
-- Data for Name: api_metadatarecord_keywords; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_metadatarecord_keywords (id, metadatarecord_id, keyword_id) FROM stdin;
\.


--
-- Data for Name: api_metadatatemplate; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_metadatatemplate (id, created_at, updated_at, name, slug, description, version, is_active) FROM stdin;
11	2026-07-23 16:04:07.794146+12	2026-07-27 10:55:19.640763+12	Lidar	lidar		1	t
\.


--
-- Data for Name: api_project; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_project (id, project_name, project_code, comments) FROM stdin;
\.


--
-- Data for Name: api_publisher; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_publisher (id, publisher_value, website, email) FROM stdin;
\.


--
-- Data for Name: api_spatialrepresentationtype; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_spatialrepresentationtype (id, spatial_representation_type_value) FROM stdin;
\.


--
-- Data for Name: api_topic; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_topic (id, topic_value) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add metadata template	9	add_metadatatemplate
26	Can change metadata template	9	change_metadatatemplate
27	Can delete metadata template	9	delete_metadatatemplate
28	Can view metadata template	9	view_metadatatemplate
29	Can add field definition	7	add_fielddefinition
30	Can change field definition	7	change_fielddefinition
31	Can delete field definition	7	delete_fielddefinition
32	Can view field definition	7	view_fielddefinition
33	Can add metadata record	8	add_metadatarecord
34	Can change metadata record	8	change_metadatarecord
35	Can delete metadata record	8	delete_metadatarecord
36	Can view metadata record	8	view_metadatarecord
37	Can add record relationship	10	add_recordrelationship
38	Can change record relationship	10	change_recordrelationship
39	Can delete record relationship	10	delete_recordrelationship
40	Can view record relationship	10	view_recordrelationship
41	Can add contact	11	add_contact
42	Can change contact	11	change_contact
43	Can delete contact	11	delete_contact
44	Can view contact	11	view_contact
45	Can add coordinate reference system	12	add_coordinatereferencesystem
46	Can change coordinate reference system	12	change_coordinatereferencesystem
47	Can delete coordinate reference system	12	delete_coordinatereferencesystem
48	Can view coordinate reference system	12	view_coordinatereferencesystem
49	Can add country	13	add_country
50	Can change country	13	change_country
51	Can delete country	13	delete_country
52	Can view country	13	view_country
53	Can add keyword	14	add_keyword
54	Can change keyword	14	change_keyword
55	Can delete keyword	14	delete_keyword
56	Can view keyword	14	view_keyword
57	Can add publisher	15	add_publisher
58	Can change publisher	15	change_publisher
59	Can delete publisher	15	delete_publisher
60	Can view publisher	15	view_publisher
61	Can add spatial representation type	16	add_spatialrepresentationtype
62	Can change spatial representation type	16	change_spatialrepresentationtype
63	Can delete spatial representation type	16	delete_spatialrepresentationtype
64	Can view spatial representation type	16	view_spatialrepresentationtype
65	Can add topic	17	add_topic
66	Can change topic	17	change_topic
67	Can delete topic	17	delete_topic
68	Can view topic	17	view_topic
69	Can add project	18	add_project
70	Can change project	18	change_project
71	Can delete project	18	delete_project
72	Can view project	18	view_project
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$to1r0pqgDzJq3oMOZJC9dw$E5CxnZeGDxZ9cvi9+N24fBa17fXxhKwwykn+TNDkj48=	2026-07-23 12:48:00.591031+12	t	admin				t	t	2026-07-23 12:47:38.01527+12
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-07-23 13:05:43.213478+12	2	Lidar Datasets (v1)	1	[{"added": {}}, {"added": {"name": "field definition", "object": "Lidar Datasets.acquisition_report_link"}}, {"added": {"name": "field definition", "object": "Lidar Datasets.additional_information"}}]	9	1
2	2026-07-23 13:10:08.712955+12	3	Espiritu Santo Topographic Orthophoto 2012 Vanuatu	1	[{"added": {}}]	8	1
3	2026-07-23 14:29:30.733934+12	7	Lidar (v1)	1	[{"added": {}}, {"added": {"name": "field definition", "object": "Lidar.project_name"}}]	9	1
4	2026-07-23 14:29:35.549616+12	7	Lidar (v1)	2	[]	9	1
5	2026-07-23 14:29:53.361053+12	8	resr	1	[{"added": {}}]	8	1
7	2026-07-23 14:42:00.160087+12	10	Lidar (v1)	1	[{"added": {}}, {"added": {"name": "field definition", "object": "Lidar.project_name"}}]	9	1
8	2026-07-23 15:14:55.109525+12	10	Lidar (v1)	2	[{"changed": {"name": "field definition", "object": "Lidar.project_name", "fields": ["Field type"]}}]	9	1
9	2026-07-23 15:49:51.204762+12	10	Lidar (v1)	2	[{"changed": {"name": "field definition", "object": "Lidar.project_name", "fields": ["Field type"]}}]	9	1
10	2026-07-27 10:43:50.309497+12	11	Lidar (v1)	2	[{"changed": {"fields": ["Name", "Slug"]}}, {"added": {"name": "field definition", "object": "Lidar.additional_information"}}, {"changed": {"name": "field definition", "object": "Lidar.acquisition_report_link", "fields": ["Name", "Label", "Field type", "Required"]}}]	9	1
11	2026-07-27 10:44:18.46402+12	11	Lidar (v1)	2	[{"changed": {"name": "field definition", "object": "Lidar.additional_information", "fields": ["Field type"]}}]	9	1
12	2026-07-27 10:54:16.743796+12	11	Lidar (v1)	2	[{"added": {"name": "field definition", "object": "Lidar.project_name"}}]	9	1
13	2026-07-27 10:55:19.65254+12	11	Lidar (v1)	2	[]	9	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	api	fielddefinition
8	api	metadatarecord
9	api	metadatatemplate
10	api	recordrelationship
11	api	contact
12	api	coordinatereferencesystem
13	api	country
14	api	keyword
15	api	publisher
16	api	spatialrepresentationtype
17	api	topic
18	api	project
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-07-23 12:46:55.808843+12
2	auth	0001_initial	2026-07-23 12:46:56.177793+12
3	admin	0001_initial	2026-07-23 12:46:56.214194+12
4	admin	0002_logentry_remove_auto_add	2026-07-23 12:46:56.245384+12
5	admin	0003_logentry_add_action_flag_choices	2026-07-23 12:46:56.25217+12
6	contenttypes	0002_remove_content_type_name	2026-07-23 12:46:56.265214+12
7	auth	0002_alter_permission_name_max_length	2026-07-23 12:46:56.276473+12
8	auth	0003_alter_user_email_max_length	2026-07-23 12:46:56.284996+12
9	auth	0004_alter_user_username_opts	2026-07-23 12:46:56.289851+12
10	auth	0005_alter_user_last_login_null	2026-07-23 12:46:56.309267+12
11	auth	0006_require_contenttypes_0002	2026-07-23 12:46:56.311619+12
12	auth	0007_alter_validators_add_error_messages	2026-07-23 12:46:56.316399+12
13	auth	0008_alter_user_username_max_length	2026-07-23 12:46:56.333118+12
14	auth	0009_alter_user_last_name_max_length	2026-07-23 12:46:56.343016+12
15	auth	0010_alter_group_name_max_length	2026-07-23 12:46:56.358278+12
16	auth	0011_update_proxy_permissions	2026-07-23 12:46:56.369584+12
17	auth	0012_alter_user_first_name_max_length	2026-07-23 12:46:56.422883+12
18	sessions	0001_initial	2026-07-23 12:46:56.446674+12
19	api	0001_initial	2026-07-23 12:54:55.861582+12
20	api	0002_delete_recordrelationship	2026-07-23 13:02:50.508823+12
21	api	0003_alter_fielddefinition_field_type	2026-07-23 16:04:06.996048+12
22	api	0004_contact_coordinatereferencesystem_country_keyword_and_more	2026-07-27 10:20:33.058759+12
23	api	0005_project_alter_fielddefinition_field_type	2026-07-27 10:53:25.834195+12
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
7nl6ycklnir6eczgfqvuipkimyeki7tt	.eJxVjDsOwjAQBe_iGlnrOP5R0nMGa71r4wBypDipEHeHSCmgfTPzXiLitta49bzEicVZKHH63RLSI7cd8B3bbZY0t3WZktwVedAurzPn5-Vw_w4q9vqtTXHOekgEHoxXwfoRjCtMWDJZVjloz7pAcAMpp0Y9ZFd0YdQAFgOJ9wfLnjeA:1wmhbU:1sa9AZU1sw_YP_froRkbhfL5SYIU9BZ7emkQOZkge70	2026-08-06 12:48:00.593887+12
zsov6bsxmpkvlzfl64ny8mgnn5q4eph7	.eJxVjDEOwjAMRe-SGUWpU1spIztniOzYpQXUSk07Ie4OlTrA-t97_-Uyb-uQt2pLHtWdHbjT7yZcHjbtQO883WZf5mldRvG74g9a_XVWe14O9-9g4Dp860Y4SkMhIqWO-t4gkrQdQQzAEFpMDCwkSGrMnIJip4RWEBIqRff-AMlBN2Y:1wmjFe:XIWTiusLsdlEJtSywm3pBrKif5ymAQFFLwfd4ZXw8Hw	2026-08-06 14:33:34.365825+12
41x6m5t18j084no73fmhyqiyu6us3zw6	.eJxVjE0OwiAYBe_C2hChEMCle89Avj-kamhS2lXj3bVJF7p9M_M2lWFdal67zHlkdVGDOv1uCPSUtgN-QLtPmqa2zCPqXdEH7fo2sbyuh_t3UKHXb02QLGMC6z0PgD6EQsVSKtGhQ-EzFfFOmENJWCx7ERPBeOuiYxOSen8AIp05NQ:1wmjGJ:Wxev9Seg3_l7fYXn-wzZAO6c-s_LXKLvAcVXnTYV3Hk	2026-08-06 14:34:15.94081+12
e08mnh7rhmhegl1yzsk8o3wo6dt77zml	.eJxVjDsOwjAQBe_iGlkO_i4lfc5grb1eHECOFCcV4u4QKQW0b2beS0Tc1hq3XpY4kbgII06_W8L8KG0HdMd2m2We27pMSe6KPGiX40zleT3cv4OKvX5r4KIYFA5Bg0fF7MDx4JAKBzZIzhV19oTgrdEZAwSVvAqgrctWUxDvD_H8N80:1wmjHn:-J46utkIzxjhrYK1ZHRK1q2OUzxDuuEUI59MtuLvNTI	2026-08-06 14:35:47.002857+12
\.


--
-- Name: api_contact_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_contact_id_seq', 1, false);


--
-- Name: api_coordinatereferencesystem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_coordinatereferencesystem_id_seq', 1, false);


--
-- Name: api_country_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_country_id_seq', 1, false);


--
-- Name: api_fielddefinition_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_fielddefinition_id_seq', 23, true);


--
-- Name: api_keyword_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_keyword_id_seq', 1, false);


--
-- Name: api_metadatarecord_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_metadatarecord_id_seq', 9, true);


--
-- Name: api_metadatarecord_keywords_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_metadatarecord_keywords_id_seq', 1, false);


--
-- Name: api_metadatatemplate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_metadatatemplate_id_seq', 11, true);


--
-- Name: api_project_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_project_id_seq', 1, false);


--
-- Name: api_publisher_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_publisher_id_seq', 1, false);


--
-- Name: api_spatialrepresentationtype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_spatialrepresentationtype_id_seq', 1, false);


--
-- Name: api_topic_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_topic_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 72, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 4, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 13, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 18, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 23, true);


--
-- Name: api_contact api_contact_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_contact
    ADD CONSTRAINT api_contact_pkey PRIMARY KEY (id);


--
-- Name: api_coordinatereferencesystem api_coordinatereferencesystem_crs_value_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_coordinatereferencesystem
    ADD CONSTRAINT api_coordinatereferencesystem_crs_value_key UNIQUE (crs_value);


--
-- Name: api_coordinatereferencesystem api_coordinatereferencesystem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_coordinatereferencesystem
    ADD CONSTRAINT api_coordinatereferencesystem_pkey PRIMARY KEY (id);


--
-- Name: api_country api_country_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_country
    ADD CONSTRAINT api_country_pkey PRIMARY KEY (id);


--
-- Name: api_country api_country_short_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_country
    ADD CONSTRAINT api_country_short_name_key UNIQUE (short_name);


--
-- Name: api_fielddefinition api_fielddefinition_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_fielddefinition
    ADD CONSTRAINT api_fielddefinition_pkey PRIMARY KEY (id);


--
-- Name: api_fielddefinition api_fielddefinition_template_id_name_a295148c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_fielddefinition
    ADD CONSTRAINT api_fielddefinition_template_id_name_a295148c_uniq UNIQUE (template_id, name);


--
-- Name: api_keyword api_keyword_keyword_value_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_keyword
    ADD CONSTRAINT api_keyword_keyword_value_key UNIQUE (keyword_value);


--
-- Name: api_keyword api_keyword_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_keyword
    ADD CONSTRAINT api_keyword_pkey PRIMARY KEY (id);


--
-- Name: api_metadatarecord_keywords api_metadatarecord_keywo_metadatarecord_id_keywor_b2d6369d_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatarecord_keywords
    ADD CONSTRAINT api_metadatarecord_keywo_metadatarecord_id_keywor_b2d6369d_uniq UNIQUE (metadatarecord_id, keyword_id);


--
-- Name: api_metadatarecord_keywords api_metadatarecord_keywords_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatarecord_keywords
    ADD CONSTRAINT api_metadatarecord_keywords_pkey PRIMARY KEY (id);


--
-- Name: api_metadatarecord api_metadatarecord_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatarecord
    ADD CONSTRAINT api_metadatarecord_pkey PRIMARY KEY (id);


--
-- Name: api_metadatatemplate api_metadatatemplate_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatatemplate
    ADD CONSTRAINT api_metadatatemplate_name_key UNIQUE (name);


--
-- Name: api_metadatatemplate api_metadatatemplate_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatatemplate
    ADD CONSTRAINT api_metadatatemplate_pkey PRIMARY KEY (id);


--
-- Name: api_metadatatemplate api_metadatatemplate_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatatemplate
    ADD CONSTRAINT api_metadatatemplate_slug_key UNIQUE (slug);


--
-- Name: api_project api_project_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_project
    ADD CONSTRAINT api_project_pkey PRIMARY KEY (id);


--
-- Name: api_project api_project_project_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_project
    ADD CONSTRAINT api_project_project_code_key UNIQUE (project_code);


--
-- Name: api_publisher api_publisher_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_publisher
    ADD CONSTRAINT api_publisher_pkey PRIMARY KEY (id);


--
-- Name: api_publisher api_publisher_publisher_value_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_publisher
    ADD CONSTRAINT api_publisher_publisher_value_key UNIQUE (publisher_value);


--
-- Name: api_spatialrepresentationtype api_spatialrepresentationtype_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_spatialrepresentationtype
    ADD CONSTRAINT api_spatialrepresentationtype_pkey PRIMARY KEY (id);


--
-- Name: api_spatialrepresentationtype api_spatialrepresentationtype_spatial_representation_type_v_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_spatialrepresentationtype
    ADD CONSTRAINT api_spatialrepresentationtype_spatial_representation_type_v_key UNIQUE (spatial_representation_type_value);


--
-- Name: api_topic api_topic_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_topic
    ADD CONSTRAINT api_topic_pkey PRIMARY KEY (id);


--
-- Name: api_topic api_topic_topic_value_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_topic
    ADD CONSTRAINT api_topic_topic_value_key UNIQUE (topic_value);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: api_coordinatereferencesystem_crs_value_f3e0198d_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_coordinatereferencesystem_crs_value_f3e0198d_like ON public.api_coordinatereferencesystem USING btree (crs_value varchar_pattern_ops);


--
-- Name: api_country_short_name_66477ea3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_country_short_name_66477ea3_like ON public.api_country USING btree (short_name varchar_pattern_ops);


--
-- Name: api_fielddefinition_name_69e5d009; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_fielddefinition_name_69e5d009 ON public.api_fielddefinition USING btree (name);


--
-- Name: api_fielddefinition_name_69e5d009_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_fielddefinition_name_69e5d009_like ON public.api_fielddefinition USING btree (name varchar_pattern_ops);


--
-- Name: api_fielddefinition_template_id_7cf124e5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_fielddefinition_template_id_7cf124e5 ON public.api_fielddefinition USING btree (template_id);


--
-- Name: api_keyword_keyword_value_c566c445_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_keyword_keyword_value_c566c445_like ON public.api_keyword USING btree (keyword_value varchar_pattern_ops);


--
-- Name: api_metadatarecord_contact_id_573c9c11; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_metadatarecord_contact_id_573c9c11 ON public.api_metadatarecord USING btree (contact_id);


--
-- Name: api_metadatarecord_coordinate_reference_system_id_0b054893; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_metadatarecord_coordinate_reference_system_id_0b054893 ON public.api_metadatarecord USING btree (coordinate_reference_system_id);


--
-- Name: api_metadatarecord_country_id_40ab29ea; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_metadatarecord_country_id_40ab29ea ON public.api_metadatarecord USING btree (country_id);


--
-- Name: api_metadatarecord_keywords_keyword_id_4bcf3a36; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_metadatarecord_keywords_keyword_id_4bcf3a36 ON public.api_metadatarecord_keywords USING btree (keyword_id);


--
-- Name: api_metadatarecord_keywords_metadatarecord_id_4f892c23; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_metadatarecord_keywords_metadatarecord_id_4f892c23 ON public.api_metadatarecord_keywords USING btree (metadatarecord_id);


--
-- Name: api_metadatarecord_owner_id_c79a2461; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_metadatarecord_owner_id_c79a2461 ON public.api_metadatarecord USING btree (owner_id);


--
-- Name: api_metadatarecord_publisher_id_e9ba5588; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_metadatarecord_publisher_id_e9ba5588 ON public.api_metadatarecord USING btree (publisher_id);


--
-- Name: api_metadatarecord_spatial_representation_type_id_02032968; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_metadatarecord_spatial_representation_type_id_02032968 ON public.api_metadatarecord USING btree (spatial_representation_type_id);


--
-- Name: api_metadatarecord_template_id_160192ce; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_metadatarecord_template_id_160192ce ON public.api_metadatarecord USING btree (template_id);


--
-- Name: api_metadatarecord_topic_id_dd5e95d5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_metadatarecord_topic_id_dd5e95d5 ON public.api_metadatarecord USING btree (topic_id);


--
-- Name: api_metadatatemplate_name_f60e3885_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_metadatatemplate_name_f60e3885_like ON public.api_metadatatemplate USING btree (name varchar_pattern_ops);


--
-- Name: api_metadatatemplate_slug_1862db1f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_metadatatemplate_slug_1862db1f_like ON public.api_metadatatemplate USING btree (slug varchar_pattern_ops);


--
-- Name: api_project_project_code_c2723b2b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_project_project_code_c2723b2b_like ON public.api_project USING btree (project_code varchar_pattern_ops);


--
-- Name: api_publisher_publisher_value_36caa1b4_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_publisher_publisher_value_36caa1b4_like ON public.api_publisher USING btree (publisher_value varchar_pattern_ops);


--
-- Name: api_spatialrepresentatio_spatial_representation_t_19e07d36_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_spatialrepresentatio_spatial_representation_t_19e07d36_like ON public.api_spatialrepresentationtype USING btree (spatial_representation_type_value varchar_pattern_ops);


--
-- Name: api_topic_topic_value_e7e4e460_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_topic_topic_value_e7e4e460_like ON public.api_topic USING btree (topic_value varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: api_fielddefinition api_fielddefinition_template_id_7cf124e5_fk_api_metad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_fielddefinition
    ADD CONSTRAINT api_fielddefinition_template_id_7cf124e5_fk_api_metad FOREIGN KEY (template_id) REFERENCES public.api_metadatatemplate(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_metadatarecord api_metadatarecord_contact_id_573c9c11_fk_api_contact_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatarecord
    ADD CONSTRAINT api_metadatarecord_contact_id_573c9c11_fk_api_contact_id FOREIGN KEY (contact_id) REFERENCES public.api_contact(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_metadatarecord api_metadatarecord_coordinate_reference_0b054893_fk_api_coord; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatarecord
    ADD CONSTRAINT api_metadatarecord_coordinate_reference_0b054893_fk_api_coord FOREIGN KEY (coordinate_reference_system_id) REFERENCES public.api_coordinatereferencesystem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_metadatarecord api_metadatarecord_country_id_40ab29ea_fk_api_country_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatarecord
    ADD CONSTRAINT api_metadatarecord_country_id_40ab29ea_fk_api_country_id FOREIGN KEY (country_id) REFERENCES public.api_country(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_metadatarecord_keywords api_metadatarecord_k_keyword_id_4bcf3a36_fk_api_keywo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatarecord_keywords
    ADD CONSTRAINT api_metadatarecord_k_keyword_id_4bcf3a36_fk_api_keywo FOREIGN KEY (keyword_id) REFERENCES public.api_keyword(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_metadatarecord_keywords api_metadatarecord_k_metadatarecord_id_4f892c23_fk_api_metad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatarecord_keywords
    ADD CONSTRAINT api_metadatarecord_k_metadatarecord_id_4f892c23_fk_api_metad FOREIGN KEY (metadatarecord_id) REFERENCES public.api_metadatarecord(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_metadatarecord api_metadatarecord_owner_id_c79a2461_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatarecord
    ADD CONSTRAINT api_metadatarecord_owner_id_c79a2461_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_metadatarecord api_metadatarecord_publisher_id_e9ba5588_fk_api_publisher_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatarecord
    ADD CONSTRAINT api_metadatarecord_publisher_id_e9ba5588_fk_api_publisher_id FOREIGN KEY (publisher_id) REFERENCES public.api_publisher(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_metadatarecord api_metadatarecord_spatial_representati_02032968_fk_api_spati; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatarecord
    ADD CONSTRAINT api_metadatarecord_spatial_representati_02032968_fk_api_spati FOREIGN KEY (spatial_representation_type_id) REFERENCES public.api_spatialrepresentationtype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_metadatarecord api_metadatarecord_template_id_160192ce_fk_api_metad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatarecord
    ADD CONSTRAINT api_metadatarecord_template_id_160192ce_fk_api_metad FOREIGN KEY (template_id) REFERENCES public.api_metadatatemplate(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_metadatarecord api_metadatarecord_topic_id_dd5e95d5_fk_api_topic_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_metadatarecord
    ADD CONSTRAINT api_metadatarecord_topic_id_dd5e95d5_fk_api_topic_id FOREIGN KEY (topic_id) REFERENCES public.api_topic(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict CiH6pyIUj5DJZhjoVGwITeWQ2Rdm3DfPvssPOPOmy75U0UZiYk4kz7XANf5SItH

