# Generated by Django 6.0.7 on 2026-07-23 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MetadataRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "creator",
                    models.CharField(
                        help_text="Person/organisation responsible", max_length=255
                    ),
                ),
                ("publisher", models.CharField(blank=True, max_length=255)),
                (
                    "date_created",
                    models.DateField(
                        help_text="Date the described resource was created"
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True, default=list, help_text="List of keyword strings"
                    ),
                ),
                ("language", models.CharField(default="en", max_length=20)),
                (
                    "rights",
                    models.CharField(
                        blank=True, help_text="Licence / usage rights", max_length=255
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Values for the template's fields",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metadata_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="api.metadatatemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.SlugField(
                        help_text="Machine key used inside record data", max_length=100
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="Human-friendly label", max_length=255),
                ),
                ("help_text", models.CharField(blank=True, max_length=500)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text (single line)"),
                            ("textarea", "Text (multi-line)"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean (yes/no)"),
                            ("date", "Date"),
                            ("datetime", "Date & time"),
                            ("url", "URL"),
                            ("email", "Email"),
                            ("select", "Select (one choice)"),
                            ("multiselect", "Select (many choices)"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Allowed values for (multi)select fields",
                    ),
                ),
                ("default", models.JSONField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="api.metadatatemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["template", "order", "id"],
                "unique_together": {("template", "name")},
            },
        ),
        migrations.CreateModel(
            name="RecordRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("derived_from", "Is derived from"),
                            ("part_of", "Is part of"),
                            ("references", "References"),
                            ("replaces", "Replaces"),
                            ("related_to", "Is related to"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_from",
                        to="api.metadatarecord",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="api.metadatarecord",
                    ),
                ),
            ],
            options={
                "unique_together": {("source", "target", "relation_type")},
            },
        ),
    ]
