# Generated by Django 6.0.7 on 2026-07-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_delete_recordrelationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fielddefinition",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text (single line)"),
                    ("textarea", "Text (multi-line)"),
                    ("integer", "Integer"),
                    ("decimal", "Decimal"),
                    ("boolean", "Boolean (yes/no)"),
                    ("date", "Date"),
                    ("datetime", "Date & time"),
                    ("url", "URL"),
                    ("email", "Email"),
                    ("select", "Select (one choice)"),
                    ("multiselect", "Select (many choices)"),
                    ("file", "File upload"),
                    ("image", "Image upload"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
