# Generated by Django 6.0.7 on 2026-07-26 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_fielddefinition_field_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=150)),
                ("lastname", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("position", models.CharField(blank=True, max_length=255)),
                ("organization", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["lastname", "firstname"],
            },
        ),
        migrations.CreateModel(
            name="CoordinateReferenceSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crs_value", models.CharField(max_length=100, unique=True)),
                ("crs_description", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "coordinate reference system",
                "verbose_name_plural": "coordinate reference systems",
                "ordering": ["crs_value"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(help_text="e.g. FJ", max_length=10, unique=True),
                ),
                ("long_name", models.CharField(help_text="e.g. Fiji", max_length=255)),
                (
                    "west_bound_longitude",
                    models.DecimalField(decimal_places=5, max_digits=9),
                ),
                (
                    "east_bound_longitude",
                    models.DecimalField(decimal_places=5, max_digits=9),
                ),
                (
                    "south_bound_latitude",
                    models.DecimalField(decimal_places=5, max_digits=9),
                ),
                (
                    "north_bound_latitude",
                    models.DecimalField(decimal_places=5, max_digits=9),
                ),
                (
                    "crs_name",
                    models.CharField(
                        help_text="CRS the bounds are given in", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "countries",
                "ordering": ["long_name"],
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword_value", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["keyword_value"],
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publisher_value", models.CharField(max_length=255, unique=True)),
                ("website", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "ordering": ["publisher_value"],
            },
        ),
        migrations.CreateModel(
            name="SpatialRepresentationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spatial_representation_type_value",
                    models.CharField(max_length=100, unique=True),
                ),
            ],
            options={
                "verbose_name": "spatial representation type",
                "verbose_name_plural": "spatial representation types",
                "ordering": ["spatial_representation_type_value"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic_value", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["topic_value"],
            },
        ),
        migrations.RemoveField(
            model_name="metadatarecord",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="metadatarecord",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="metadatarecord",
            name="description",
        ),
        migrations.RemoveField(
            model_name="metadatarecord",
            name="identifier",
        ),
        migrations.RemoveField(
            model_name="metadatarecord",
            name="rights",
        ),
        # publisher changes from free text to a lookup FK: drop and re-add
        # rather than casting varchar -> bigint in place.
        migrations.RemoveField(
            model_name="metadatarecord",
            name="publisher",
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="abstract",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="access_constraints",
            field=models.CharField(
                choices=[("private", "Private"), ("open", "Open")],
                default="private",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="license",
            field=models.CharField(default="Other (Not Open)", max_length=255),
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="lineage",
            field=models.TextField(default="none"),
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="metadata_standard_language",
            field=models.CharField(default="English", max_length=100),
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="metadata_standard_name",
            field=models.CharField(default="MEDIN", max_length=100),
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="metadata_standard_version",
            field=models.CharField(default="3.1.2", max_length=50),
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="temporal_coverage_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="temporal_coverage_to",
            field=models.DateField(
                blank=True, help_text="Leave empty if coverage is ongoing", null=True
            ),
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="update_frequency",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="version",
            field=models.CharField(default="1.0.0", max_length=50),
        ),
        migrations.RemoveField(
            model_name="metadatarecord",
            name="keywords",
        ),
        migrations.AlterField(
            model_name="metadatarecord",
            name="language",
            field=models.CharField(default="English", max_length=100),
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="contact",
            field=models.ForeignKey(
                default=1,
                help_text="Person to contact about this record",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="api.contact",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="coordinate_reference_system",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="api.coordinatereferencesystem",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="country",
            field=models.ForeignKey(
                default=1,
                help_text="Supplies the geographic bounding box and its CRS name",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="api.country",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="api.publisher",
            ),
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="spatial_representation_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="api.spatialrepresentationtype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="topic",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="api.topic",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metadatarecord",
            name="keywords",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="api.keyword"
            ),
        ),
    ]
