# Generated by Django 6.0.7 on 2026-07-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_contact_coordinatereferencesystem_country_keyword_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("project_code", models.CharField(max_length=50, unique=True)),
                ("comments", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["project_name"],
            },
        ),
        migrations.AlterField(
            model_name="fielddefinition",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text (single line)"),
                    ("textarea", "Text (multi-line)"),
                    ("integer", "Integer"),
                    ("decimal", "Decimal"),
                    ("boolean", "Boolean (yes/no)"),
                    ("date", "Date"),
                    ("datetime", "Date & time"),
                    ("url", "URL"),
                    ("email", "Email"),
                    ("select", "Select (one choice)"),
                    ("multiselect", "Select (many choices)"),
                    ("file", "File upload"),
                    ("image", "Image upload"),
                    ("project", "Project (lookup)"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
