# Generated by Django 6.0.7 on 2026-07-26 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_project_alter_fielddefinition_field_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElasticsearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Internal label", max_length=255, unique=True
                    ),
                ),
                (
                    "index_name",
                    models.CharField(
                        help_text="Elasticsearch index to write into, e.g. dms-records",
                        max_length=255,
                    ),
                ),
                (
                    "only_published",
                    models.BooleanField(
                        default=True, help_text="Send published records only"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Limit to records of this template; empty means all templates",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elasticsearch_indexes",
                        to="api.metadatatemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elasticsearch index",
                "verbose_name_plural": "Elasticsearch indexes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ElasticsearchFieldMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Dotted path on the record: a core field (title), a related lookup attribute (country.long_name), or a template value (data.project)",
                        max_length=200,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        help_text="Key in the Elasticsearch document; defaults to the source path with dots replaced by underscores",
                        max_length=200,
                    ),
                ),
                (
                    "es_type",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("keyword", "keyword"),
                            ("integer", "integer"),
                            ("float", "float"),
                            ("boolean", "boolean"),
                            ("date", "date"),
                            ("geo_shape", "geo_shape"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="api.elasticsearchindex",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elasticsearch field",
                "verbose_name_plural": "Elasticsearch fields",
                "ordering": ["index", "order", "id"],
                "unique_together": {("index", "source")},
            },
        ),
    ]
