# Generated by Django 6.0.7 on 2026-07-26 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_elasticsearchindex_elasticsearchfieldmap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elasticsearchfieldmap",
            name="source",
            field=models.CharField(
                choices=[
                    ("id", "id"),
                    ("title", "title"),
                    ("abstract", "abstract"),
                    ("contact.firstname", "contact — firstname"),
                    ("contact.lastname", "contact — lastname"),
                    ("contact.email", "contact — email"),
                    ("contact.position", "contact — position"),
                    ("contact.organization", "contact — organization"),
                    ("language", "language"),
                    ("version", "version"),
                    ("country.short_name", "country — short_name"),
                    ("country.long_name", "country — long_name"),
                    ("west_bound_longitude", "west_bound_longitude"),
                    ("east_bound_longitude", "east_bound_longitude"),
                    ("south_bound_latitude", "south_bound_latitude"),
                    ("north_bound_latitude", "north_bound_latitude"),
                    ("crs_name", "crs_name"),
                    ("coordinate_reference_system.crs_value", "crs_value"),
                    ("coordinate_reference_system.crs_description", "crs_description"),
                    ("publisher.publisher_value", "publisher — publisher_value"),
                    ("publisher.website", "publisher — website"),
                    ("publisher.email", "publisher — email"),
                    ("topic.topic_value", "topic — topic_value"),
                    ("keywords.keyword_value", "keywords — keyword_value (list)"),
                    ("access_constraints", "access_constraints"),
                    ("license", "license"),
                    ("temporal_coverage_from", "temporal_coverage_from"),
                    ("temporal_coverage_to", "temporal_coverage_to"),
                    ("metadata_standard_name", "metadata_standard_name"),
                    ("metadata_standard_version", "metadata_standard_version"),
                    ("metadata_standard_language", "metadata_standard_language"),
                    ("update_frequency", "update_frequency"),
                    ("lineage", "lineage"),
                    (
                        "spatial_representation_type.spatial_representation_type_value",
                        "spatial_representation_type_value",
                    ),
                    ("status", "status"),
                    ("created_at", "created_at"),
                    ("updated_at", "updated_at"),
                ],
                help_text="Field of the metadata record to send",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="elasticsearchindex",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Limit which records are indexed to this template; empty means records of every template. Template ('data') fields are never sent.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elasticsearch_indexes",
                to="api.metadatatemplate",
            ),
        ),
    ]
