# Generated by Django 6.0.7 on 2026-07-26 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_elasticsearchfieldmap_source_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elasticsearchindex",
            name="template",
        ),
    ]
