"""
Django settings for dms project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a .env file at the project root.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-8qinlh7va9dipv)^6$j(k!a0jj_ca7o0yldef$uz#+%r8vs@@%",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# nginx terminates TLS and forwards plain HTTP - without this, request.scheme
# is always "http" behind the proxy, which breaks the CSRF Referer check and
# any is_secure()-gated redirect once DEBUG=False.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Set when served behind a path-prefixed reverse proxy (e.g. https://host/dms)
# so Django generates admin/media/static URLs (redirects, {% static %},
# upload links) with that prefix instead of the app's own root. Left unset
# for local dev, where the app is hit directly with no prefix.
FORCE_SCRIPT_NAME = os.getenv("DJANGO_FORCE_SCRIPT_NAME") or None


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    # Local
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves collected static files (admin CSS/JS) directly from gunicorn in
    # production - there's no nginx in front of this container, unlike
    # frontend/.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "dms.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "dms.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "dms"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

# Read-only connection to the legacy FastAPI backend's database, used only by
# the one-time `migrate_from_legacy` management command (api/management/
# commands/migrate_from_legacy.py) - not a Django-managed database, so it's
# a plain psycopg2 connection, not a second DATABASES entry.
LEGACY_DB_NAME = os.getenv("LEGACY_DB_NAME", "dms")
LEGACY_DB_USER = os.getenv("LEGACY_DB_USER", "dms_user")
LEGACY_DB_PASSWORD = os.getenv("LEGACY_DB_PASSWORD", "dms_password")
LEGACY_DB_HOST = os.getenv("LEGACY_DB_HOST", "localhost")
LEGACY_DB_PORT = os.getenv("LEGACY_DB_PORT", "5432")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Absolute (not relative) so it's used as-is: Django's script-prefix
# auto-prepending for relative STATIC_URL/MEDIA_URL (see LazySettings.
# _add_script_prefix) resolves and caches on first access, which whitenoise
# triggers once at worker boot - before any request has set the prefix -
# permanently locking in the un-prefixed value for that worker's lifetime.
STATIC_URL = os.getenv("DJANGO_STATIC_URL", "static/")
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (user uploads). Absolute for the same reason as STATIC_URL
# above. Unlike /dms/admin/ and /dms/static/, the nginx block for this must
# forward the request path unchanged (not stripped) - urls.py's static()
# helper builds its URL pattern directly from this value, so an absolute
# MEDIA_URL only routes correctly if PATH_INFO still has the /dms prefix on
# it when it reaches Django.
MEDIA_URL = os.getenv("DJANGO_MEDIA_URL", "media/")
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Django REST Framework
# https://www.django-rest-framework.org/
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
}

# JWT lifetimes matched to the legacy backend's ACCESS_TOKEN_EXPIRE_MINUTES/
# REFRESH_TOKEN_EXPIRE_DAYS, so the frontend's existing token-lifetime
# expectations don't need to change. Custom views in api/auth_views.py issue/
# refresh these (matching the legacy request/response shapes lib/auth.js
# expects) rather than SimpleJWT's default TokenObtainPairView.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=365),
    "ROTATE_REFRESH_TOKENS": False,
}

# CORS — allow your frontend origin(s)
# https://github.com/adamchainz/django-cors-headers
CORS_ALLOWED_ORIGINS = [
    origin
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000"
    ).split(",")
    if origin
]

# Elasticsearch — used by the push_to_elasticsearch management command and
# api.elasticsearch_sync (real-time sync on save/delete). Which record fields
# are sent for *custom* indexes is configured per index in the admin
# (api.ElasticsearchIndex); the legacy-compatibility "metadata" index's shape
# is hard-coded in api.elasticsearch_sync.build_legacy_metadata_document.
ELASTICSEARCH_URL = os.getenv("ELASTICSEARCH_URL", "http://localhost:9200")
ELASTICSEARCH_API_KEY = os.getenv("ELASTICSEARCH_API_KEY", "")
# Basic auth, used when security is enabled (the docker-compose ES service
# has xpack.security.enabled=true) and no api key is configured.
ELASTICSEARCH_USERNAME = os.getenv("ELASTICSEARCH_USERNAME", "elastic")
ELASTICSEARCH_PASSWORD = os.getenv("ELASTICSEARCH_PASSWORD", "T2NlYW5wb3J0YWwyMDE3")

# Used to build absolute links (e.g. acquisition report downloads) in
# Elasticsearch documents - mirrors the legacy backend's FRONTEND_URL.
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")

# pygeoapi collection sync (api.pygeoapi_sync) - regenerates pygeoapi's
# config whenever an ElasticsearchIndex is saved/deleted in the admin, so
# each index gets its own pygeoapi collection without hand-editing YAML.
# Repo layout: backend/ and pygeoapi/ are sibling directories.
PYGEOAPI_DIR = Path(os.getenv("PYGEOAPI_DIR", str(BASE_DIR.parent / "pygeoapi")))
# Also restart the local pygeoapi dev process (pygeoapi/restart.sh) after
# regenerating its config, so the new collection goes live immediately.
# pygeoapi only reads its config once at startup, so without this a restart
# would otherwise have to be done by hand. Local dev convenience only - set
# to False (or override PYGEOAPI_RESTART_COMMAND) for any shared/production
# deployment where pygeoapi runs elsewhere (e.g. its own Docker container).
PYGEOAPI_AUTO_RESTART = os.getenv("PYGEOAPI_AUTO_RESTART", "True") == "True"
# Optional override, e.g. "docker restart dms-pygeoapi" - defaults to
# running pygeoapi/restart.sh directly (or via `wsl.exe -d Ubuntu` if this
# Django process itself is running natively on Windows rather than in WSL).
PYGEOAPI_RESTART_COMMAND = os.getenv("PYGEOAPI_RESTART_COMMAND", "")
